version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: my-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ~/Documents/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 